Replaced size calculation with a more optimal version
mozilla/filter-cascade pull request #1
Opened 2019-07-10 14:27 UTC by bowlinearl

I'm not sure what the origin of the calc_size() formulation used in this implementation was, but it's a bit sub-optimal. Here are some plots showing the size of the existing "Moz" bloom filters versus the 1.44*n*log_2(1/p) formulation from the CRLite paper:

![results](https://user-images.githubusercontent.com/8768998/60976958-9bbfb000-a2fc-11e9-8671-66946e978a89.png)

All three plots show how filters using the two size formulas vary as the number of elements (n) and false positive rate (FPR, p) vary. The top graph is total filter sizes in bits, the middle graph is difference in size in bits, and the bottom graph is percentage increase in size.

Depending on how things work out with math.ceil(), the existing formulation produces filters that are 0-5% oversized. 

I also added some additional, optional parameters to the filter cascade constructor, so downstream users can parameterize the free space overhead and minimum filter sizes.

2019-07-10 21:04 UTC, jcjones requested changes
LGTM, just want to remove those commented-out lines.

2019-07-10 21:04 UTC, jcjones commented on filtercascade/__init__.py
> +        #return math.ceil(1 - (nHashFuncs * (elements + 0.5) / math.log(
Old code should be removed rather than commented out.

2019-07-11 15:05 UTC, jcjones approved these changes
Thanks!

2019-07-12 09:39 UTC, mozmark approved these changes
Excellent. Thanks!

2019-07-12 09:39 UTC, merged